spring.application.name=GYMAPP

spring.datasource.url=jdbc:mysql://localhost:3306/eclypse_db
spring.datasource.username=root
spring.datasource.password=ansh1505@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true